dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./clients/loc-poc-angular/node_modules

before_install:
  - cd clients/loc-poc-angular

install:
  - yarn install

before_deploy:
  - yarn run build --prod --base-href /loc-poc-angular/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: clients/loc-poc-angular/dist/loc-poc-angular
  on:
    branch: master
